import {useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
const FORMATTER = '\n\n'



export default function Home() {
  const [content, setContent] = useState("")

  function FormUploadData() {
    function changeHandler(e) {
      if(e.target.files.length > 0) {
        const reader = new FileReader()
        reader.readAsText(e.target.files[0])
        reader.onload = function(e) {
            var raw = reader.result;
            let formatted = raw.split(FORMATTER)
            setContent(formatted)
        };
      }
    }
    return (
          <form method="post" enctype="multipart/form-data">
            <div>
              <label htmlFor="file">Choose file to upload</label>
              <input 
                onChange={changeHandler}
                accept="text/*"
                type="file" 
                id="file" 
                name="file"/>
            </div>
          </form>
    )
  }

  function ListParagraphs({content}) {

    [selected, setSelected] = useState(new Array(content.length).fill(false))

    function Paragraph({isSelected, onClick, children}) {
      return (
        <p onClick={onClick}>
          {children}
        </p>
      )
    }

    return (
      <ul>
          {
            content.map((entry, index) => {
            return (<li>
                      <Paragraph 
                        isSelected={selected[index]}
                        key={index}>
                        {entry}
                      </Paragraph>
                    </li>
                    )
            })
          } 
      </ul>

    )
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <FormUploadData/>
        <div>
        {content.length > 0 && (

        )}
        </div>
      </main>
    </>
  )
}
